<a href="https://colab.research.google.com/github/asmita-mukherjee/Closing-price-prediction-of-Indian-Stock-/blob/main/Tensors.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

### following from https://pytorch.org/tutorials/index.html

In [1]:
import torch

In [2]:
import numpy as np

In [3]:
def print_tensor(t):
  print(f"The tensor {t} and its shape {t.shape} and its dtype {t.dtype} and device of tensor {t.device}")

## Different ways of initializing tensors

#### Directly from data

In [4]:
data = [[1,2],[3,4]]
t = torch.tensor(data)
print(f"The tensor {t} and its shape {t.shape}")

The tensor tensor([[1, 2],
        [3, 4]]) and its shape torch.Size([2, 2])


In [5]:
data = [[1,2,3],[4,5,6],[7,8,9]]
t = torch.tensor(data)
print(f"The Tensor {t} and its shape {t.shape}")

The Tensor tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) and its shape torch.Size([3, 3])


#### from numpy array

In [6]:
np_array = np.array(data)
t = torch.tensor(data)
print_tensor(t)

The tensor tensor([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]) and its shape torch.Size([3, 3]) and its dtype torch.int64 and device of tensor cpu


From another tensor (using its shape and dtype)

In [7]:
t = torch.rand_like(t,dtype=torch.float)

In [8]:
print_tensor(t)

The tensor tensor([[0.4787, 0.1151, 0.2143],
        [0.0381, 0.5897, 0.9122],
        [0.6027, 0.3694, 0.7464]]) and its shape torch.Size([3, 3]) and its dtype torch.float32 and device of tensor cpu


In [9]:
t = torch.ones_like(t)
print_tensor(t)


The tensor tensor([[1., 1., 1.],
        [1., 1., 1.],
        [1., 1., 1.]]) and its shape torch.Size([3, 3]) and its dtype torch.float32 and device of tensor cpu


## With random or constant values:

In [10]:
shape = (2,5)

In [11]:
t1 = torch.randn(shape)
print_tensor(t1)

The tensor tensor([[-0.6996, -1.0864, -1.5471,  0.7001,  1.4896],
        [ 0.1137,  1.3957,  0.3689, -2.0577,  0.4820]]) and its shape torch.Size([2, 5]) and its dtype torch.float32 and device of tensor cpu


In [12]:
t2 = torch.ones(shape,dtype=torch.int)
print_tensor(t2)

The tensor tensor([[1, 1, 1, 1, 1],
        [1, 1, 1, 1, 1]], dtype=torch.int32) and its shape torch.Size([2, 5]) and its dtype torch.int32 and device of tensor cpu


In [13]:
t3 = torch.rand(shape)
print_tensor(t3)

The tensor tensor([[0.0664, 0.9389, 0.8262, 0.7077, 0.4102],
        [0.2190, 0.3039, 0.0795, 0.0891, 0.3567]]) and its shape torch.Size([2, 5]) and its dtype torch.float32 and device of tensor cpu


## Tensor Operations

In [16]:
if torch.cuda.is_available():
  t3 = t3.to('cuda')

print_tensor(t3)

The tensor tensor([[0.0664, 0.9389, 0.8262, 0.7077, 0.4102],
        [0.2190, 0.3039, 0.0795, 0.0891, 0.3567]], device='cuda:0') and its shape torch.Size([2, 5]) and its dtype torch.float32 and device of tensor cuda:0


In [19]:
torch.cuda.memory_snapshot()

[{'device': 0,
  'address': 140266367352832,
  'total_size': 2097152,
  'allocated_size': 512,
  'active_size': 512,
  'requested_size': 40,
  'stream': 0,
  'segment_type': 'small',
  'blocks': [{'size': 512, 'requested_size': 40, 'state': 'active_allocated'},
   {'size': 2096640, 'requested_size': 8, 'state': 'inactive'}]}]

In [27]:
t4 = torch.ones(3,4,3)

print("before")
print_tensor(t4)

t4[1,:,:] = 0 

print("After")
print_tensor(t4)



before
The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu
After
The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.],
         [0., 0., 0.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu


In [28]:
t4 = torch.ones(3,4,3)

print("before")
print_tensor(t4)

t4[:,1,:] = 0 #make 1st axis all 0s

print("After")
print_tensor(t4)



before
The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu
After
The tensor tensor([[[1., 1., 1.],
         [0., 0., 0.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [0., 0., 0.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu


In [29]:
t4 = torch.ones(3,4,3)

print("before")
print_tensor(t4)

t4[:,:,1] = 0 #make 1st axis all 0s

print("After")
print_tensor(t4)


before
The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu
After
The tensor tensor([[[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]],

        [[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]],

        [[1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.],
         [1., 0., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu


Hence the 1st axis denote which of the matrix we are taking about and [1,:,:] would indicate the 2nd matrix


The 2nd axis denote the row index of each matrix , hence [:,1,:] indicates the 2nd row of each matrix


The 3rd axis denote the column index of each matrix, hence [:,:,1] indicates the 2nd column of each matrix




### Joining tensors

In [30]:
tensor = torch.ones(3,4,3)

In [31]:
print_tensor(tensor)

The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 4, 3]) and its dtype torch.float32 and device of tensor cpu


#### Joining along different dimensions

In [32]:
tensor_new = torch.cat([tensor,tensor],dim = 0)

print_tensor(tensor_new)

The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([6, 4, 3]) and its dtype torch.float32 and device of tensor cpu


In [33]:
tensor_new = torch.cat([tensor,tensor],dim = 1)

print_tensor(tensor_new)

The tensor tensor([[[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.],
         [1., 1., 1.]]]) and its shape torch.Size([3, 8, 3]) and its dtype torch.float32 and device of tensor cpu


In [34]:
tensor_new = torch.cat([tensor,tensor],dim = 2)

print_tensor(tensor_new)

The tensor tensor([[[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]],

        [[1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.],
         [1., 1., 1., 1., 1., 1.]]]) and its shape torch.Size([3, 4, 6]) and its dtype torch.float32 and device of tensor cpu


### Multiplication and addition

In [39]:
arr1 = [[1,2,3],[4,5,6]] #2*3

arr2 = [[2],[2],[2]] # 3*1 

t1 = torch.tensor(arr1)
t2 = torch.tensor(arr2)

In [40]:
t1.matmul(t2)

tensor([[12],
        [30]])

In [41]:
t1@t2

tensor([[12],
        [30]])

In [42]:
t1.add_(5)

tensor([[ 6,  7,  8],
        [ 9, 10, 11]])

#### Numpy arrays and tensors 

Both the numpy array and the tensor shares the same memory

In [43]:
t = torch.ones(5)
print(f"t: {t}")
n = t.numpy()
print(f"n: {n}")

t: tensor([1., 1., 1., 1., 1.])
n: [1. 1. 1. 1. 1.]


In [44]:
t.add_(1)
print(f"t: {t}")
print(f"n: {n}")

t: tensor([2., 2., 2., 2., 2.])
n: [2. 2. 2. 2. 2.]


When 1 is added it is added to both t and n
